<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_- Use maximum 30 character_phone_numb_7c938a</name>
   <tag></tag>
   <elementGuidId>96a9edd3-79ae-4234-b95d-fdcd042977d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone_numberRegisterPage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone_numberRegisterPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4de70bb-6e00-48bc-acc5-a44539df8960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_numberRegisterPage</value>
      <webElementGuid>2b389e1c-407f-4d3e-8637-b18de94d36ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4712689-326f-4249-9241-c4b720fe6843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>328c1ea2-26c3-4922-bdda-95180f43082d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope</value>
      <webElementGuid>a6fe788e-8a51-4a69-bb1d-a47cfab0eee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCover&quot;)/div[2]/div[@class=&quot;spliter&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope&quot;]</value>
      <webElementGuid>d7ed6741-3b1c-489a-9e99-e5e8e4faa03c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone_numberRegisterPage']</value>
      <webElementGuid>12267031-b1ae-4917-92e5-a171768aaea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCover']/div[2]/div[2]/sec-view/div/input</value>
      <webElementGuid>a170bb6b-54c8-4d61-8de4-1cade962fda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/sec-view/div/input</value>
      <webElementGuid>a6e1d4c1-7da7-46e6-a9eb-5f0df89e991c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phone_numberRegisterPage' and @type = 'text']</value>
      <webElementGuid>42f49756-87c6-4b7a-bf45-c89b6a76d34f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
