<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT</name>
   <tag></tag>
   <elementGuidId>136453d4-a9d9-49d0-90ca-e97549f550a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#next_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55c55023-5aa5-4c2c-983b-41e5f78ce3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_btn</value>
      <webElementGuid>87e6bfab-be3f-4d9c-b71d-1c488b8e2eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b392369e-6870-4a64-8091-e14f401b7603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>shippingDetails_next()</value>
      <webElementGuid>d313d75b-5c2f-486d-aa34-7ca03c4c4397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button nextBtn marginTop75 ng-scope</value>
      <webElementGuid>3e35b2b4-4b8e-469a-8cd9-f3b25d2bf13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>56534a2e-5d3e-40fc-8ffa-7b6b802179c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>7a4610fa-33ae-4c20-96dd-e608615618d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userSection&quot;)/div[1]/div[@class=&quot;mobileBtnHandler&quot;]/button[@id=&quot;next_btn&quot;]</value>
      <webElementGuid>9a6b7736-c3a3-4afd-94e0-a2ef050bdf53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='next_btn']</value>
      <webElementGuid>035db09b-26ac-4d13-90bf-634cc8a64bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userSection']/div/div[3]/button</value>
      <webElementGuid>c5095271-091d-4cc7-9722-8d8686aac3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHIPPING BY:'])[1]/following::button[1]</value>
      <webElementGuid>56a0d026-fb5e-4abd-96e2-85e948223d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit shipping details'])[1]/following::button[1]</value>
      <webElementGuid>ba384546-11fa-4223-bd9d-cb840a055db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipient details'])[1]/preceding::button[1]</value>
      <webElementGuid>a134e9fa-9122-437d-9a49-565916a7b29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::button[1]</value>
      <webElementGuid>babb7ddd-437e-4659-b89e-e8147746b845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT']/parent::*</value>
      <webElementGuid>e9335eec-7ec8-4a79-8ae7-d9ff77182265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>20096a6a-0645-4ba7-af2e-f2d4cc7045f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'next_btn' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>eb529aac-3f0c-41ac-91db-91c652569ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
