<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAY NOW</name>
   <tag></tag>
   <elementGuidId>df75eea5-e0e4-4187-8362-3d7acadfb49a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay_now_btn_MasterCredit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pay_now_btn_MasterCredit' and @name = 'pay_now_btn_MasterCredit' and (text() = 'PAY NOW' or . = 'PAY NOW')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pay_now_btn_MasterCredit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc7b5332-9da4-4771-9525-4d8e9614477f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay_now_btn_MasterCredit</value>
      <webElementGuid>8f780310-38ce-4730-9d17-b6908842bdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pay_now_btn_MasterCredit</value>
      <webElementGuid>ec1b0e65-aa36-46ea-8e9a-01fc2c8a73dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium float-button a-button ng-binding</value>
      <webElementGuid>bf5e26fc-14d3-47cb-bfd4-13d4c8427c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>payNow_manual()</value>
      <webElementGuid>4ae3d8f9-8cc0-4d96-8cfc-020ba998996c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07c831c2-b497-4abf-b276-f06f8d446900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAY NOW</value>
      <webElementGuid>25641c54-7978-4f93-b0b2-ca4bb9f5131e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay_now_btn_MasterCredit&quot;)</value>
      <webElementGuid>48bcad1e-6cd8-4bf3-a7e0-ae640421ee8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay_now_btn_MasterCredit']</value>
      <webElementGuid>6e0f7674-f215-4ef8-a674-a7d2cada12dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[3]/div[2]/label/button</value>
      <webElementGuid>325a40e7-5bde-4f5c-b72d-50ed366a99bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to shipping details'])[2]/following::button[1]</value>
      <webElementGuid>703ecf1c-29c7-4ea9-b83b-febafc5074d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[1]</value>
      <webElementGuid>27d7e017-a357-4eb2-a063-be5c945d8305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice'])[2]/preceding::button[1]</value>
      <webElementGuid>c6b915ba-0b9b-430d-b510-69c3924932f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::button[1]</value>
      <webElementGuid>e2d7a7e2-8e99-4168-a279-0209d8b502b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/button</value>
      <webElementGuid>94dc12e1-2bd1-47ac-a8c8-3d6e6d1691c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay_now_btn_MasterCredit' and @name = 'pay_now_btn_MasterCredit' and (text() = 'PAY NOW' or . = 'PAY NOW')]</value>
      <webElementGuid>06daf56d-e25b-47f7-9715-1dbe3181728d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
