<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>e25994c6-b1a2-410e-8abe-db50e85dd795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentMethod']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Master credit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d79bd5df-4793-414c-aacd-c102600d0312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/Master_credit.png</value>
      <webElementGuid>b8988211-af06-4cee-afc5-6693113b144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Master credit</value>
      <webElementGuid>940ed842-2cfb-4cc6-b7f7-93246c1aedc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[@class=&quot;paymentMethods&quot;]/div[@class=&quot;imgRadioButton selected&quot;]/img[1]</value>
      <webElementGuid>86eae725-2e3d-4e11-96e2-5b80de5b56e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div/div[2]/img</value>
      <webElementGuid>223ae726-5950-4ef4-b86f-782d9a785628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Master credit']</value>
      <webElementGuid>85a44a43-b744-498b-8794-bf976ccdd47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>3e079eb5-70bf-4d99-9a28-a02fc8299307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'css/images/Master_credit.png' and @alt = 'Master credit']</value>
      <webElementGuid>77a350a5-8f67-4337-b41f-03706aae3fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
